# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-active
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: nginx-active
#   template:
#     metadata:
#       labels:
#         app: nginx-active
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.17
#         ports:
#         - containerPort: 80
