apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx

resources:
  - deployment-blue.yaml
  - deployment-green.yaml
  - service-preview.yaml
  - service.yaml
  - rollout.yaml
